/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function applyAIFilter(base64Image: string, prompt: string) {
  const model = "gemini-2.5-flash-image";
  
  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image.split(',')[1],
            mimeType: "image/png",
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image generated by AI");
}

export async function suggestItemName(base64Images: string[]) {
  const model = "gemini-3-flash-preview";
  
  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        ...base64Images.map(img => ({
          inlineData: {
            data: img.split(',')[1],
            mimeType: "image/png",
          },
        })),
        {
          text: "Based on these photos of a product for sale online, suggest a short, professional, and descriptive item name (3-6 words). Return ONLY the name, no extra text.",
        },
      ],
    },
  });

  return response.text?.trim() || "Item";
}

export const AI_PROMPTS = {
  ENHANCE: "Enhance this product photo for an online store. Improve lighting, clarity, and colors while keeping it natural.",
  CLEAN_BACKGROUND: "Remove the background and replace it with a clean, professional studio white background. Keep the product (clothing/accessory) perfectly intact.",
  LIFESTYLE: "Place this item in a professional lifestyle setting suitable for an online fashion store. Ensure the lighting matches.",
};
