package com.snapsell.nativecamera.ui.editor

import android.content.ContentValues
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.ColorMatrix
import android.graphics.ColorMatrixColorFilter
import android.graphics.Matrix
import android.graphics.Paint
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Base64
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.activity.compose.BackHandler
import coil.compose.AsyncImage
import com.snapsell.nativecamera.ui.settings.AppSettings
import com.snapsell.nativecamera.ui.settings.AppSettings.getSaveLocation
import com.snapsell.nativecamera.ui.theme.Primary
import com.snapsell.nativecamera.ui.theme.SurfaceDark
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.net.HttpURLConnection
import java.net.URL

// Per-photo edit state
data class PhotoAdjustments(
    val exposure: Float = 0f,
    val contrast: Float = 0f,
    val scale: Float = 1f,
    val appliedFilter: AiFilter? = null
)

enum class AiFilter(val label: String, val prompt: String, val color: Color) {
    ENHANCE("Enhance", "Enhance this product photo for an online store. Improve lighting, sharpness, and color balance while keeping it natural.", Color(0xFF60A5FA)),
    WHITE_BG("White BG", "Remove the background and replace it with a clean, professional studio white background.", Color(0xFF34D399)),
    LIFESTYLE("Lifestyle", "Place this item in a professional lifestyle setting that would appeal to online shoppers.", Color(0xFFC084FC))
}

enum class EditorTab(val label: String) {
    ADJUST("Adjust"),
    AI_FILTERS("AI Filters"),
    CROP("Crop")
}

// Toast state
data class ToastState(
    val message: String,
    val isVisible: Boolean = false,
    val isWarning: Boolean = false
)

@Composable
fun EditorScreen(
    photoPaths: List<String>,
    onBack: () -> Unit
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    // Multi-photo state
    var selectedIndex by remember { mutableIntStateOf(0) }
    val adjustments = remember { mutableStateMapOf<Int, PhotoAdjustments>() }
    var applyToAll by remember { mutableStateOf(false) }

    // Tab state
    var activeTab by remember { mutableStateOf(EditorTab.ADJUST) }

    // AI listing generation
    var generatedTitle by remember { mutableStateOf("") }
    var generatedDescription by remember { mutableStateOf("") }
    var generatedPrice by remember { mutableStateOf("") }
    var isGenerating by remember { mutableStateOf(false) }
    var hasGenerated by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf<String?>(null) }

    // Item name
    var itemName by remember { mutableStateOf("") }
    var isSuggestingName by remember { mutableStateOf(false) }

    // AI filter processing
    var isFilterProcessing by remember { mutableStateOf(false) }

    // Save state
    var isSaving by remember { mutableStateOf(false) }

    // Toast
    var toastState by remember { mutableStateOf(ToastState("")) }

    // Auto-dismiss toast
    LaunchedEffect(toastState.isVisible) {
        if (toastState.isVisible) {
            val duration = if (toastState.isWarning) 5000L else 3500L
            delay(duration)
            toastState = toastState.copy(isVisible = false)
        }
    }

    // Current photo adjustments
    val currentAdjustments = adjustments[selectedIndex] ?: PhotoAdjustments()

    fun updateAdjustments(newAdj: PhotoAdjustments) {
        adjustments[selectedIndex] = newAdj
        if (applyToAll) {
            photoPaths.indices.forEach { i ->
                if (i != selectedIndex) adjustments[i] = newAdj
            }
        }
    }

    BackHandler(onBack = onBack)

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(Color(0xFF0A0E14), Color(0xFF111820))
                )
            )
    ) {
        Column(modifier = Modifier.fillMaxSize()) {
            // Header bar
            HeaderBar(
                itemName = itemName,
                onItemNameChange = { itemName = it },
                onSuggestName = {
                    if (photoPaths.isNotEmpty()) {
                        scope.launch {
                            isSuggestingName = true
                            try {
                                val apiKey = AppSettings.getGeminiApiKey(context)
                                if (apiKey.isBlank()) {
                                    errorMessage = "No Gemini API key set."
                                    return@launch
                                }
                                val name = suggestItemName(apiKey, photoPaths.first())
                                itemName = name
                            } catch (e: Exception) {
                                errorMessage = e.message
                            } finally {
                                isSuggestingName = false
                            }
                        }
                    }
                },
                isSuggestingName = isSuggestingName,
                isSaving = isSaving,
                onSave = {
                    scope.launch {
                        isSaving = true
                        try {
                            val savedCount = saveAllPhotos(context, photoPaths, adjustments.toMap(), itemName)
                            toastState = ToastState("Saved $savedCount photo(s).")
                        } catch (e: Exception) {
                            toastState = ToastState("Saved to fallback. Check permissions.", isWarning = true)
                        } finally {
                            isSaving = false
                        }
                    }
                },
                onBack = onBack
            )

            // Preview area
            Box(
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth(),
                contentAlignment = Alignment.Center
            ) {
                // Main image
                val photoFile = File(photoPaths[selectedIndex])
                val adj = currentAdjustments
                val brightness = 1f + (adj.exposure / 200f)
                val contrast = 1f + (adj.contrast / 200f)

                Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(horizontal = 16.dp, vertical = 8.dp),
                    contentAlignment = Alignment.Center
                ) {
                    AsyncImage(
                        model = photoFile,
                        contentDescription = "Photo ${selectedIndex + 1}",
                        modifier = Modifier
                            .fillMaxSize()
                            .graphicsLayer {
                                scaleX = adj.scale.coerceIn(0.1f, 2f)
                                scaleY = adj.scale.coerceIn(0.1f, 2f)
                            },
                        contentScale = ContentScale.Fit
                    )

                    // Brightness/contrast overlay simulation via semi-transparent layer
                    if (adj.exposure != 0f || adj.contrast != 0f) {
                        Box(
                            modifier = Modifier
                                .fillMaxSize()
                                .graphicsLayer {
                                    // Use alpha to simulate brightness adjustments
                                    alpha = if (adj.exposure > 0) {
                                        (adj.exposure / 400f).coerceIn(0f, 0.3f)
                                    } else {
                                        (-adj.exposure / 400f).coerceIn(0f, 0.3f)
                                    }
                                }
                                .background(
                                    if (adj.exposure > 0) Color.White else Color.Black
                                )
                        )
                    }

                    // Processing overlay
                    if (isFilterProcessing) {
                        Box(
                            modifier = Modifier
                                .fillMaxSize()
                                .background(Color.Black.copy(alpha = 0.6f)),
                            contentAlignment = Alignment.Center
                        ) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                CircularProgressIndicator(
                                    modifier = Modifier.size(48.dp),
                                    color = Primary,
                                    strokeWidth = 3.dp
                                )
                                Spacer(Modifier.height(12.dp))
                                Text(
                                    "AI Processing...",
                                    color = Color.White,
                                    fontFamily = FontFamily.Monospace,
                                    fontSize = 14.sp,
                                    fontWeight = FontWeight.Bold
                                )
                            }
                        }
                    }
                }

                // Photo counter
                if (photoPaths.size > 1) {
                    Text(
                        "${selectedIndex + 1} / ${photoPaths.size}",
                        color = Color.White.copy(alpha = 0.5f),
                        fontSize = 11.sp,
                        fontFamily = FontFamily.Monospace,
                        modifier = Modifier
                            .align(Alignment.TopEnd)
                            .padding(16.dp)
                            .background(Color.Black.copy(alpha = 0.5f), RoundedCornerShape(8.dp))
                            .padding(horizontal = 8.dp, vertical = 4.dp)
                    )
                }
            }

            // Thumbnail strip
            if (photoPaths.size > 1) {
                ThumbnailStrip(
                    photoPaths = photoPaths,
                    selectedIndex = selectedIndex,
                    onSelect = { selectedIndex = it },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            // Bottom control panel
            BottomControlPanel(
                activeTab = activeTab,
                onTabChange = { activeTab = it },
                applyToAll = applyToAll,
                onApplyToAllChange = { applyToAll = it },
                adjustments = currentAdjustments,
                onAdjustmentsChange = { newAdj -> updateAdjustments(newAdj) },
                onApplyFilter = { filter ->
                    scope.launch {
                        isFilterProcessing = true
                        try {
                            val apiKey = AppSettings.getGeminiApiKey(context)
                            if (apiKey.isBlank()) {
                                errorMessage = "No Gemini API key set."
                                return@launch
                            }
                            val result = applyAiFilter(context, apiKey, photoPaths[selectedIndex], filter)
                            // Replace the file with the processed result
                            val outputFile = File(photoPaths[selectedIndex])
                            FileOutputStream(outputFile).use { fos ->
                                result.compress(Bitmap.CompressFormat.JPEG, 95, fos)
                            }
                            adjustments[selectedIndex] = currentAdjustments.copy(appliedFilter = filter)
                        } catch (e: Exception) {
                            errorMessage = e.message ?: "AI filter failed"
                        } finally {
                            isFilterProcessing = false
                        }
                    }
                },
                isFilterProcessing = isFilterProcessing
            )
        }

        // Generate listing button (floating)
        if (!hasGenerated) {
            FloatingActionButton(
                onClick = {
                    scope.launch {
                        isGenerating = true
                        errorMessage = null
                        try {
                            val apiKey = AppSettings.getGeminiApiKey(context)
                            if (apiKey.isBlank()) {
                                errorMessage = "No Gemini API key set. Go to Settings → AI Configuration."
                                return@launch
                            }
                            val result = generateListingDescription(apiKey, photoPaths.first())
                            generatedTitle = result.title
                            generatedDescription = result.description
                            generatedPrice = result.suggestedPrice
                            if (itemName.isBlank()) itemName = result.title
                            hasGenerated = true
                        } catch (e: Exception) {
                            errorMessage = e.message ?: "Failed to generate listing"
                        } finally {
                            isGenerating = false
                        }
                    }
                },
                modifier = Modifier
                    .align(Alignment.BottomEnd)
                    .padding(end = 16.dp, bottom = 16.dp),
                containerColor = Primary,
                contentColor = Color(0xFF005A3C)
            ) {
                if (isGenerating) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(24.dp),
                        strokeWidth = 2.dp,
                        color = Color(0xFF005A3C)
                    )
                } else {
                    Icon(Icons.Default.AutoAwesome, "Generate Listing")
                }
            }
        }

        // Generated listing overlay
        if (hasGenerated) {
            ListingOverlay(
                title = generatedTitle,
                onTitleChange = { generatedTitle = it },
                price = generatedPrice,
                onPriceChange = { generatedPrice = it },
                description = generatedDescription,
                onDescriptionChange = { generatedDescription = it },
                errorMessage = errorMessage,
                isGenerating = isGenerating,
                onRegenerate = {
                    scope.launch {
                        isGenerating = true
                        errorMessage = null
                        try {
                            val apiKey = AppSettings.getGeminiApiKey(context)
                            if (apiKey.isBlank()) {
                                errorMessage = "No Gemini API key set."
                                return@launch
                            }
                            val result = generateListingDescription(apiKey, photoPaths.first())
                            generatedTitle = result.title
                            generatedDescription = result.description
                            generatedPrice = result.suggestedPrice
                        } catch (e: Exception) {
                            errorMessage = e.message ?: "Failed to generate listing"
                        } finally {
                            isGenerating = false
                        }
                    }
                },
                onDismiss = { hasGenerated = false },
                context = context
            )
        }

        // Error toast
        errorMessage?.let { error ->
            LaunchedEffect(error) {
                delay(5000)
                errorMessage = null
            }
        }

        // Error bar
        errorMessage?.let { error ->
            Box(
                modifier = Modifier
                    .align(Alignment.BottomCenter)
                    .padding(bottom = 80.dp)
                    .padding(horizontal = 32.dp)
            ) {
                Text(
                    error,
                    color = MaterialTheme.colorScheme.error,
                    fontSize = 12.sp,
                    fontFamily = FontFamily.Monospace,
                    modifier = Modifier
                        .background(Color(0xFF1A0000), RoundedCornerShape(8.dp))
                        .border(1.dp, MaterialTheme.colorScheme.error.copy(alpha = 0.3f), RoundedCornerShape(8.dp))
                        .padding(12.dp)
                )
            }
        }

        // Toast notification
        AnimatedVisibility(
            visible = toastState.isVisible,
            enter = fadeIn() + slideInVertically(initialOffsetY = { it }),
            exit = fadeOut() + slideOutVertically(targetOffsetY = { it }),
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .padding(bottom = 24.dp)
        ) {
            Text(
                toastState.message,
                color = Color.White,
                fontSize = 14.sp,
                fontFamily = FontFamily.Monospace,
                modifier = Modifier
                    .background(
                        if (toastState.isWarning) Color(0xFF4A3000).copy(alpha = 0.95f)
                        else SurfaceDark.copy(alpha = 0.95f),
                        RoundedCornerShape(50)
                    )
                    .padding(horizontal = 24.dp, vertical = 12.dp)
            )
        }
    }
}

@Composable
private fun HeaderBar(
    itemName: String,
    onItemNameChange: (String) -> Unit,
    onSuggestName: () -> Unit,
    isSuggestingName: Boolean,
    isSaving: Boolean,
    onSave: () -> Unit,
    onBack: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .background(SurfaceDark.copy(alpha = 0.5f))
            .padding(horizontal = 8.dp, vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        IconButton(onClick = onBack) {
            Icon(
                Icons.Default.Close,
                contentDescription = "Close",
                tint = Color.White.copy(alpha = 0.7f)
            )
        }

        // Item name input
        OutlinedTextField(
            value = itemName,
            onValueChange = onItemNameChange,
            placeholder = {
                Text(
                    "Enter item name...",
                    color = Color.White.copy(alpha = 0.3f),
                    fontSize = 13.sp,
                    fontFamily = FontFamily.Monospace
                )
            },
            singleLine = true,
            modifier = Modifier.weight(1f),
            shape = RoundedCornerShape(50),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = Primary.copy(alpha = 0.5f),
                unfocusedBorderColor = Color.White.copy(alpha = 0.1f),
                cursorColor = Primary,
                focusedTextColor = Color.White,
                unfocusedTextColor = Color.White
            ),
            textStyle = LocalTextStyle.current.copy(
                fontFamily = FontFamily.Monospace,
                fontSize = 13.sp
            ),
            trailingIcon = {
                if (isSuggestingName) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(18.dp),
                        strokeWidth = 2.dp,
                        color = Color(0xFF60A5FA)
                    )
                } else {
                    IconButton(onClick = onSuggestName) {
                        Icon(
                            Icons.Default.AutoAwesome,
                            contentDescription = "AI Suggest",
                            tint = Color(0xFF60A5FA),
                            modifier = Modifier.size(18.dp)
                        )
                    }
                }
            }
        )

        Spacer(Modifier.width(8.dp))

        // Finish/Save button
        Button(
            onClick = onSave,
            enabled = !isSaving,
            shape = RoundedCornerShape(50),
            colors = ButtonDefaults.buttonColors(
                containerColor = Primary,
                contentColor = Color(0xFF005A3C),
                disabledContainerColor = Primary.copy(alpha = 0.5f)
            ),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp)
        ) {
            if (isSaving) {
                CircularProgressIndicator(
                    modifier = Modifier.size(16.dp),
                    strokeWidth = 2.dp,
                    color = Color(0xFF005A3C)
                )
                Spacer(Modifier.width(4.dp))
                Text("Saving...", fontFamily = FontFamily.Monospace, fontSize = 12.sp, fontWeight = FontWeight.Bold)
            } else {
                Icon(Icons.Default.Save, contentDescription = null, modifier = Modifier.size(16.dp))
                Spacer(Modifier.width(4.dp))
                Text("Finish", fontFamily = FontFamily.Monospace, fontSize = 12.sp, fontWeight = FontWeight.Bold)
            }
        }
    }
}

@Composable
private fun ThumbnailStrip(
    photoPaths: List<String>,
    selectedIndex: Int,
    onSelect: (Int) -> Unit,
    modifier: Modifier = Modifier
) {
    Row(
        modifier = modifier
            .horizontalScroll(rememberScrollState())
            .padding(horizontal = 16.dp, vertical = 8.dp),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        photoPaths.forEachIndexed { index, path ->
            val isSelected = index == selectedIndex
            AsyncImage(
                model = File(path),
                contentDescription = "Thumb ${index + 1}",
                modifier = Modifier
                    .size(56.dp)
                    .clip(RoundedCornerShape(8.dp))
                    .then(
                        if (isSelected) Modifier.border(2.dp, Color.White, RoundedCornerShape(8.dp))
                        else Modifier.border(1.dp, Color.White.copy(alpha = 0.1f), RoundedCornerShape(8.dp))
                    )
                    .then(if (!isSelected) Modifier.graphicsLayer { alpha = 0.5f } else Modifier)
                    .clickable { onSelect(index) },
                contentScale = ContentScale.Crop
            )
        }
    }
}

@Composable
private fun BottomControlPanel(
    activeTab: EditorTab,
    onTabChange: (EditorTab) -> Unit,
    applyToAll: Boolean,
    onApplyToAllChange: (Boolean) -> Unit,
    adjustments: PhotoAdjustments,
    onAdjustmentsChange: (PhotoAdjustments) -> Unit,
    onApplyFilter: (AiFilter) -> Unit,
    isFilterProcessing: Boolean
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(SurfaceDark)
            .clip(RoundedCornerShape(topStart = 24.dp, topEnd = 24.dp))
    ) {
        // Tab row + Apply to All toggle
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 8.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            // Tab buttons
            Row(horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                EditorTab.entries.forEach { tab ->
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        modifier = Modifier
                            .clip(RoundedCornerShape(8.dp))
                            .clickable { onTabChange(tab) }
                            .background(
                                if (activeTab == tab) Color.White.copy(alpha = 0.1f)
                                else Color.Transparent
                            )
                            .padding(horizontal = 12.dp, vertical = 6.dp)
                    ) {
                        Icon(
                            when (tab) {
                                EditorTab.ADJUST -> Icons.Default.Tune
                                EditorTab.AI_FILTERS -> Icons.Default.AutoAwesome
                                EditorTab.CROP -> Icons.Default.Crop
                            },
                            contentDescription = tab.label,
                            tint = if (activeTab == tab) Color.White else Color.White.copy(alpha = 0.4f),
                            modifier = Modifier.size(18.dp)
                        )
                        Text(
                            tab.label,
                            color = if (activeTab == tab) Color.White else Color.White.copy(alpha = 0.4f),
                            fontSize = 10.sp,
                            fontFamily = FontFamily.Monospace,
                            fontWeight = FontWeight.Bold
                        )
                    }
                }
            }

            // Apply to All toggle
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(
                    "ALL",
                    color = Color.White.copy(alpha = 0.4f),
                    fontSize = 10.sp,
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Bold
                )
                Spacer(Modifier.width(4.dp))
                Switch(
                    checked = applyToAll,
                    onCheckedChange = onApplyToAllChange,
                    modifier = Modifier.height(20.dp),
                    colors = SwitchDefaults.colors(
                        checkedTrackColor = Primary,
                        checkedThumbColor = Color.White,
                        uncheckedTrackColor = Color.White.copy(alpha = 0.1f),
                        uncheckedThumbColor = Color.White.copy(alpha = 0.5f)
                    )
                )
            }
        }

        // Tab content
        AnimatedContent(
            targetState = activeTab,
            transitionSpec = { fadeIn(tween(200)) togetherWith fadeOut(tween(200)) },
            label = "tab_content"
        ) { tab ->
            when (tab) {
                EditorTab.ADJUST -> AdjustTab(
                    adjustments = adjustments,
                    onAdjustmentsChange = onAdjustmentsChange
                )
                EditorTab.AI_FILTERS -> AiFiltersTab(
                    onApplyFilter = onApplyFilter,
                    isProcessing = isFilterProcessing
                )
                EditorTab.CROP -> CropTab()
            }
        }
    }
}

@Composable
private fun AdjustTab(
    adjustments: PhotoAdjustments,
    onAdjustmentsChange: (PhotoAdjustments) -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 8.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        // Exposure
        SliderRow(
            icon = { Icon(Icons.Default.WbSunny, "Exposure", tint = Color.White.copy(alpha = 0.6f), modifier = Modifier.size(18.dp)) },
            label = "EXP",
            value = adjustments.exposure,
            range = -100f..100f,
            onValueChange = { onAdjustmentsChange(adjustments.copy(exposure = it)) }
        )

        // Contrast
        SliderRow(
            icon = { Icon(Icons.Default.Contrast, "Contrast", tint = Color.White.copy(alpha = 0.6f), modifier = Modifier.size(18.dp)) },
            label = "CON",
            value = adjustments.contrast,
            range = -100f..100f,
            onValueChange = { onAdjustmentsChange(adjustments.copy(contrast = it)) }
        )

        // Scale
        SliderRow(
            icon = { Icon(Icons.Default.AspectRatio, "Scale", tint = Color.White.copy(alpha = 0.6f), modifier = Modifier.size(18.dp)) },
            label = "SCL",
            value = (adjustments.scale * 100f) - 100f, // map 0.1-2.0 to -90..100 for display
            range = -90f..100f,
            onValueChange = { onAdjustmentsChange(adjustments.copy(scale = ((it + 100f) / 100f).coerceIn(0.1f, 2f))) },
            displayValue = String.format("%.1f", adjustments.scale)
        )
    }
}

@Composable
private fun SliderRow(
    icon: @Composable () -> Unit,
    label: String,
    value: Float,
    range: ClosedFloatingPointRange<Float>,
    onValueChange: (Float) -> Unit,
    displayValue: String = value.toInt().toString()
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically
    ) {
        icon()
        Spacer(Modifier.width(8.dp))
        Slider(
            value = value,
            onValueChange = onValueChange,
            valueRange = range,
            modifier = Modifier.weight(1f),
            colors = SliderDefaults.colors(
                thumbColor = Primary,
                activeTrackColor = Primary,
                inactiveTrackColor = Color.White.copy(alpha = 0.1f)
            )
        )
        Spacer(Modifier.width(8.dp))
        Text(
            displayValue,
            color = Color.White.copy(alpha = 0.6f),
            fontSize = 12.sp,
            fontFamily = FontFamily.Monospace,
            modifier = Modifier.width(40.dp)
        )
    }
}

@Composable
private fun AiFiltersTab(
    onApplyFilter: (AiFilter) -> Unit,
    isProcessing: Boolean
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 12.dp),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        AiFilter.entries.forEach { filter ->
            Box(
                modifier = Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(12.dp))
                    .background(Color.White.copy(alpha = 0.05f))
                    .clickable(enabled = !isProcessing) { onApplyFilter(filter) }
                    .padding(12.dp),
                contentAlignment = Alignment.Center
            ) {
                Column(
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.Center
                ) {
                    Icon(
                        when (filter) {
                            AiFilter.ENHANCE -> Icons.Default.AutoFixHigh
                            AiFilter.WHITE_BG -> Icons.Default.Layers
                            AiFilter.LIFESTYLE -> Icons.Default.Image
                        },
                        contentDescription = filter.label,
                        tint = filter.color,
                        modifier = Modifier.size(20.dp)
                    )
                    Spacer(Modifier.height(4.dp))
                    Text(
                        filter.label,
                        color = filter.color,
                        fontSize = 10.sp,
                        fontFamily = FontFamily.Monospace,
                        fontWeight = FontWeight.Bold
                    )
                }
            }
        }
    }
}

@Composable
private fun CropTab() {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 24.dp),
        contentAlignment = Alignment.Center
    ) {
        Text(
            "Crop tool coming soon in next update",
            color = Color.White.copy(alpha = 0.4f),
            fontSize = 13.sp,
            fontFamily = FontFamily.Monospace
        )
    }
}

@Composable
private fun ListingOverlay(
    title: String,
    onTitleChange: (String) -> Unit,
    price: String,
    onPriceChange: (String) -> Unit,
    description: String,
    onDescriptionChange: (String) -> Unit,
    errorMessage: String?,
    isGenerating: Boolean,
    onRegenerate: () -> Unit,
    onDismiss: () -> Unit,
    context: Context
) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black.copy(alpha = 0.8f))
            .clickable(onClick = onDismiss),
        contentAlignment = Alignment.Center
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .fillMaxHeight(0.85f)
                .background(SurfaceDark, RoundedCornerShape(16.dp))
                .clip(RoundedCornerShape(16.dp))
                .verticalScroll(rememberScrollState())
                .padding(20.dp)
                .clickable(enabled = false) {} // prevent dismiss when clicking inside
        ) {
            // Header
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    "AI Listing",
                    color = Primary,
                    fontSize = 16.sp,
                    fontWeight = FontWeight.Bold,
                    fontFamily = FontFamily.Monospace
                )
                IconButton(onClick = onDismiss) {
                    Icon(Icons.Default.Close, "Close", tint = Color.White.copy(alpha = 0.5f))
                }
            }

            Spacer(Modifier.height(12.dp))

            // Title
            Text("TITLE", color = Primary, fontSize = 11.sp, fontWeight = FontWeight.Bold, fontFamily = FontFamily.Monospace)
            Spacer(Modifier.height(4.dp))
            OutlinedTextField(
                value = title,
                onValueChange = onTitleChange,
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(8.dp),
                colors = textFieldColors(),
                textStyle = LocalTextStyle.current.copy(fontFamily = FontFamily.Monospace, fontSize = 15.sp, fontWeight = FontWeight.SemiBold)
            )

            Spacer(Modifier.height(12.dp))

            // Price
            Text("SUGGESTED PRICE", color = Primary, fontSize = 11.sp, fontWeight = FontWeight.Bold, fontFamily = FontFamily.Monospace)
            Spacer(Modifier.height(4.dp))
            OutlinedTextField(
                value = price,
                onValueChange = onPriceChange,
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(8.dp),
                colors = OutlinedTextFieldDefaults.colors(
                    focusedBorderColor = Primary,
                    unfocusedBorderColor = Color.White.copy(alpha = 0.15f),
                    cursorColor = Primary,
                    focusedTextColor = Primary,
                    unfocusedTextColor = Primary
                ),
                textStyle = LocalTextStyle.current.copy(fontFamily = FontFamily.Monospace, fontSize = 18.sp, fontWeight = FontWeight.Bold)
            )

            Spacer(Modifier.height(12.dp))

            // Description
            Text("DESCRIPTION", color = Primary, fontSize = 11.sp, fontWeight = FontWeight.Bold, fontFamily = FontFamily.Monospace)
            Spacer(Modifier.height(4.dp))
            OutlinedTextField(
                value = description,
                onValueChange = onDescriptionChange,
                modifier = Modifier.fillMaxWidth().heightIn(min = 120.dp),
                shape = RoundedCornerShape(8.dp),
                colors = textFieldColors(),
                textStyle = LocalTextStyle.current.copy(fontFamily = FontFamily.Monospace, fontSize = 13.sp, lineHeight = 18.sp)
            )

            Spacer(Modifier.height(16.dp))

            // Action buttons
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                // Copy
                OutlinedButton(
                    onClick = {
                        val text = buildString {
                            append(title); append("\n\n")
                            if (price.isNotBlank()) append("Price: $price\n\n")
                            append(description)
                        }
                        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as android.content.ClipboardManager
                        clipboard.setPrimaryClip(android.content.ClipData.newPlainText("Listing", text))
                    },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    colors = ButtonDefaults.outlinedButtonColors(contentColor = Primary)
                ) {
                    Icon(Icons.Default.ContentCopy, null, modifier = Modifier.size(16.dp))
                    Spacer(Modifier.width(4.dp))
                    Text("Copy", fontFamily = FontFamily.Monospace, fontSize = 12.sp)
                }

                // Share
                Button(
                    onClick = {
                        val text = buildString {
                            append(title); append("\n\n")
                            if (price.isNotBlank()) append("Price: $price\n\n")
                            append(description)
                        }
                        val intent = android.content.Intent(android.content.Intent.ACTION_SEND).apply {
                            type = "text/plain"
                            putExtra(android.content.Intent.EXTRA_TEXT, text)
                        }
                        context.startActivity(android.content.Intent.createChooser(intent, "Share Listing"))
                    },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = Primary, contentColor = Color(0xFF005A3C))
                ) {
                    Icon(Icons.Default.Share, null, modifier = Modifier.size(16.dp))
                    Spacer(Modifier.width(4.dp))
                    Text("Share", fontFamily = FontFamily.Monospace, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                }
            }

            Spacer(Modifier.height(8.dp))

            // Regenerate
            OutlinedButton(
                onClick = onRegenerate,
                enabled = !isGenerating,
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(12.dp),
                colors = ButtonDefaults.outlinedButtonColors(contentColor = Color(0xFF60A5FA))
            ) {
                if (isGenerating) {
                    CircularProgressIndicator(modifier = Modifier.size(16.dp), strokeWidth = 2.dp, color = Color(0xFF60A5FA))
                    Spacer(Modifier.width(8.dp))
                } else {
                    Icon(Icons.Default.AutoAwesome, null, modifier = Modifier.size(16.dp))
                    Spacer(Modifier.width(8.dp))
                }
                Text(
                    if (isGenerating) "Generating..." else "Regenerate",
                    fontFamily = FontFamily.Monospace, fontSize = 12.sp
                )
            }
        }
    }
}

@Composable
private fun textFieldColors() = OutlinedTextFieldDefaults.colors(
    focusedBorderColor = Primary,
    unfocusedBorderColor = Color.White.copy(alpha = 0.15f),
    cursorColor = Primary,
    focusedTextColor = Color.White,
    unfocusedTextColor = Color.White
)

// ==================== DATA / API HELPERS ====================

private data class ListingResult(
    val title: String,
    val description: String,
    val suggestedPrice: String
)

private suspend fun suggestItemName(apiKey: String, photoPath: String): String =
    withContext(Dispatchers.IO) {
        val base64Image = compressImageForApi(photoPath)

        val url = URL("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$apiKey")

        val jsonBody = JSONObject().apply {
            put("contents", JSONArray().apply {
                put(JSONObject().apply {
                    put("parts", JSONArray().apply {
                        put(JSONObject().apply {
                            put("inline_data", JSONObject().apply {
                                put("mime_type", "image/jpeg")
                                put("data", base64Image)
                            })
                        })
                        put(JSONObject().apply {
                            put("text", "What is this item? Reply with only a short product name (under 40 characters), no quotes, no extra text.")
                        })
                    })
                })
            })
            put("generationConfig", JSONObject().apply {
                put("temperature", 0.4)
                put("maxOutputTokens", 60)
            })
        }

        val connection = url.openConnection() as HttpURLConnection
        connection.requestMethod = "POST"
        connection.setRequestProperty("Content-Type", "application/json")
        connection.doOutput = true

        try {
            connection.outputStream.use { os ->
                os.write(jsonBody.toString().toByteArray(Charsets.UTF_8))
            }
            val responseCode = connection.responseCode
            val responseBody = if (responseCode == 200) {
                connection.inputStream.bufferedReader().readText()
            } else {
                val errorBody = connection.errorStream?.bufferedReader()?.readText() ?: "Unknown error"
                throw Exception("API error ($responseCode): $errorBody")
            }
            val responseJson = JSONObject(responseBody)
            val text = responseJson.getJSONArray("candidates")
                .getJSONObject(0).getJSONObject("content")
                .getJSONArray("parts").getJSONObject(0).getString("text")
            text.trim().removeSurrounding("\"").removeSurrounding("*")
        } finally {
            connection.disconnect()
        }
    }

private suspend fun generateListingDescription(apiKey: String, photoPath: String): ListingResult =
    withContext(Dispatchers.IO) {
        val base64Image = compressImageForApi(photoPath)

        val url = URL("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$apiKey")

        val jsonBody = JSONObject().apply {
            put("contents", JSONArray().apply {
                put(JSONObject().apply {
                    put("parts", JSONArray().apply {
                        put(JSONObject().apply {
                            put("inline_data", JSONObject().apply {
                                put("mime_type", "image/jpeg")
                                put("data", base64Image)
                            })
                        })
                        put(JSONObject().apply {
                            put("text", """You are a professional e-commerce listing creator. Analyze this product photo and create a compelling marketplace listing.

Return your response as valid JSON with exactly these fields:
{
  "title": "A clear, searchable product title (under 80 chars)",
  "description": "A compelling product description with key features, condition notes, and selling points. Use bullet points with • for readability.",
  "suggestedPrice": "A reasonable price estimate with $ symbol, or blank if impossible to estimate"
}

Be specific about the item. If it's not a product, describe what you see as if creating a listing anyway.""")
                        })
                    })
                })
            })
            put("generationConfig", JSONObject().apply {
                put("temperature", 0.7)
                put("maxOutputTokens", 1024)
            })
        }

        val connection = url.openConnection() as HttpURLConnection
        connection.requestMethod = "POST"
        connection.setRequestProperty("Content-Type", "application/json")
        connection.doOutput = true

        try {
            connection.outputStream.use { os ->
                os.write(jsonBody.toString().toByteArray(Charsets.UTF_8))
            }

            val responseCode = connection.responseCode
            val responseBody = if (responseCode == 200) {
                connection.inputStream.bufferedReader().readText()
            } else {
                val errorBody = connection.errorStream?.bufferedReader()?.readText() ?: "Unknown error"
                throw Exception("API error ($responseCode): $errorBody")
            }

            parseGeminiResponse(responseBody)
        } finally {
            connection.disconnect()
        }
    }

private fun compressImageForApi(imagePath: String, maxDim: Int = 1024): String {
    val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
    BitmapFactory.decodeFile(imagePath, bounds)
    var sampleSize = 1
    while (bounds.outWidth / (sampleSize * 2) >= maxDim && bounds.outHeight / (sampleSize * 2) >= maxDim) {
        sampleSize *= 2
    }
    val loadOpts = BitmapFactory.Options().apply { inSampleSize = sampleSize }
    val bitmap = BitmapFactory.decodeFile(imagePath, loadOpts) ?: throw Exception("Cannot read photo")
    val scale = minOf(1f, minOf(maxDim.toFloat() / bitmap.width, maxDim.toFloat() / bitmap.height))
    val scaled = if (scale < 1f) {
        Bitmap.createScaledBitmap(bitmap, (bitmap.width * scale).toInt(), (bitmap.height * scale).toInt(), true)
            .also { if (it !== bitmap) bitmap.recycle() }
    } else bitmap
    val baos = java.io.ByteArrayOutputStream()
    scaled.compress(Bitmap.CompressFormat.JPEG, 85, baos)
    scaled.recycle()
    return Base64.encodeToString(baos.toByteArray(), Base64.NO_WRAP)
}

private suspend fun applyAiFilter(context: Context, apiKey: String, photoPath: String, filter: AiFilter): Bitmap =
    withContext(Dispatchers.IO) {
        val base64Image = compressImageForApi(photoPath)

        val url = URL("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=$apiKey")

        val jsonBody = JSONObject().apply {
            put("contents", JSONArray().apply {
                put(JSONObject().apply {
                    put("parts", JSONArray().apply {
                        put(JSONObject().apply {
                            put("inline_data", JSONObject().apply {
                                put("mime_type", "image/jpeg")
                                put("data", base64Image)
                            })
                        })
                        put(JSONObject().apply {
                            put("text", filter.prompt + " Return the result as an image.")
                        })
                    })
                })
            })
            put("generationConfig", JSONObject().apply {
                put("responseModalities", JSONArray().apply {
                    put("TEXT")
                    put("IMAGE")
                })
                put("temperature", 0.4)
            })
        }

        val connection = url.openConnection() as HttpURLConnection
        connection.requestMethod = "POST"
        connection.setRequestProperty("Content-Type", "application/json")
        connection.doOutput = true

        try {
            connection.outputStream.use { os ->
                os.write(jsonBody.toString().toByteArray(Charsets.UTF_8))
            }

            val responseCode = connection.responseCode
            if (responseCode != 200) {
                val errorBody = connection.errorStream?.bufferedReader()?.readText() ?: "Unknown error"
                throw Exception("API error ($responseCode): $errorBody")
            }

            val responseBody = connection.inputStream.bufferedReader().readText()
            val responseJson = JSONObject(responseBody)
            val parts = responseJson.getJSONArray("candidates")
                .getJSONObject(0).getJSONObject("content")
                .getJSONArray("parts")

            // Look for image data in response
            for (i in 0 until parts.length()) {
                val part = parts.getJSONObject(i)
                if (part.has("inline_data")) {
                    val imageData = part.getJSONObject("inline_data").getString("data")
                    val imageBytesResult = Base64.decode(imageData, Base64.DEFAULT)
                    return@withContext BitmapFactory.decodeByteArray(imageBytesResult, 0, imageBytesResult.size)
                        ?: throw Exception("Failed to decode AI image")
                }
            }

            // If no image returned, apply a software-based enhancement as fallback
            val original = BitmapFactory.decodeFile(photoPath) ?: throw Exception("Cannot read photo")
            val enhanced = applySoftwareFilter(original, filter)
            return@withContext enhanced
        } finally {
            connection.disconnect()
        }
    }

private fun applySoftwareFilter(bitmap: Bitmap, filter: AiFilter): Bitmap {
    val result = Bitmap.createBitmap(bitmap.width, bitmap.height, Bitmap.Config.ARGB_8888)
    val canvas = Canvas(result)
    val paint = Paint()

    when (filter) {
        AiFilter.ENHANCE -> {
            // Increase contrast and saturation
            val cm = ColorMatrix()
            cm.setSaturation(1.3f)
            val contrastMatrix = ColorMatrix(floatArrayOf(
                1.2f, 0f, 0f, 0f, -15f,
                0f, 1.2f, 0f, 0f, -15f,
                0f, 0f, 1.2f, 0f, -15f,
                0f, 0f, 0f, 1f, 0f
            ))
            cm.postConcat(contrastMatrix)
            paint.colorFilter = ColorMatrixColorFilter(cm)
        }
        AiFilter.WHITE_BG -> {
            // Brighten to push toward white background
            val cm = ColorMatrix(floatArrayOf(
                1.1f, 0f, 0f, 0f, 30f,
                0f, 1.1f, 0f, 0f, 30f,
                0f, 0f, 1.1f, 0f, 30f,
                0f, 0f, 0f, 1f, 0f
            ))
            paint.colorFilter = ColorMatrixColorFilter(cm)
        }
        AiFilter.LIFESTYLE -> {
            // Warm tones
            val cm = ColorMatrix(floatArrayOf(
                1.1f, 0.05f, 0f, 0f, 10f,
                0f, 1.05f, 0f, 0f, 5f,
                0f, 0f, 1f, 0f, 0f,
                0f, 0f, 0f, 1f, 0f
            ))
            paint.colorFilter = ColorMatrixColorFilter(cm)
        }
    }

    canvas.drawBitmap(bitmap, 0f, 0f, paint)
    return result
}

private fun parseGeminiResponse(responseBody: String): ListingResult {
    val responseJson = JSONObject(responseBody)
    val candidates = responseJson.getJSONArray("candidates")
    val content = candidates.getJSONObject(0).getJSONObject("content")
    val parts = content.getJSONArray("parts")
    val text = parts.getJSONObject(0).getString("text")

    val jsonStr = extractJson(text)
    val listing = JSONObject(jsonStr)

    return ListingResult(
        title = listing.optString("title", "Untitled"),
        description = listing.optString("description", ""),
        suggestedPrice = listing.optString("suggestedPrice", "")
    )
}

private fun extractJson(text: String): String {
    val jsonBlockRegex = Regex("```(?:json)?\\s*\\n?([\\s\\S]*?)\\n?```")
    val match = jsonBlockRegex.find(text)
    if (match != null) {
        return match.groupValues[1].trim()
    }

    val braceStart = text.indexOf('{')
    val braceEnd = text.lastIndexOf('}')
    if (braceStart >= 0 && braceEnd > braceStart) {
        return text.substring(braceStart, braceEnd + 1)
    }

    return text.trim()
}

private suspend fun saveAllPhotos(
    context: Context,
    photoPaths: List<String>,
    adjustments: Map<Int, PhotoAdjustments>,
    itemName: String
): Int = withContext(Dispatchers.IO) {
    var savedCount = 0
    val saveDir = getSaveLocation(context)
    val folder = if (saveDir.isNotBlank()) {
        File(saveDir)
    } else {
        File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), "SnapSell")
    }

    if (!folder.exists()) folder.mkdirs()

    photoPaths.forEachIndexed { index, path ->
        try {
            val sourceFile = File(path)
            if (!sourceFile.exists()) return@forEachIndexed

            val adj = adjustments[index] ?: PhotoAdjustments()

            // Apply adjustments to bitmap
            val original = BitmapFactory.decodeFile(path) ?: return@forEachIndexed
            val processed = applyAdjustmentsToBitmap(original, adj)

            // Generate filename
            val timestamp = System.currentTimeMillis()
            val sanitizedName = itemName.replace(Regex("[^a-zA-Z0-9_-]"), "_").take(30)
            val filename = if (sanitizedName.isNotBlank()) {
                "${sanitizedName}_${index + 1}.jpg"
            } else {
                "SnapSell_${timestamp}_${index + 1}.jpg"
            }

            val outputFile = File(folder, filename)
            FileOutputStream(outputFile).use { fos ->
                processed.compress(Bitmap.CompressFormat.JPEG, 95, fos)
            }

            // Also add to MediaStore for gallery visibility
            addImageToMediaStore(context, outputFile, filename)

            savedCount++
        } catch (e: Exception) {
            // Try fallback save
            try {
                val sourceFile = File(path)
                if (sourceFile.exists()) {
                    val fallbackDir = File(context.getExternalFilesDir(Environment.DIRECTORY_PICTURES), "SnapSell")
                    fallbackDir.mkdirs()
                    val fallbackFile = File(fallbackDir, "SnapSell_fallback_${index + 1}.jpg")
                    sourceFile.copyTo(fallbackFile, overwrite = true)
                    savedCount++
                }
            } catch (_: Exception) {}
        }
    }

    savedCount
}

private fun applyAdjustmentsToBitmap(bitmap: Bitmap, adj: PhotoAdjustments): Bitmap {
    if (adj.exposure == 0f && adj.contrast == 0f && adj.scale == 1f) {
        return bitmap
    }

    var result = bitmap

    // Apply brightness and contrast
    if (adj.exposure != 0f || adj.contrast != 0f) {
        val brightness = adj.exposure / 2f // -50 to +50
        val contrast = 1f + (adj.contrast / 100f)
        val cm = ColorMatrix(floatArrayOf(
            contrast, 0f, 0f, 0f, brightness,
            0f, contrast, 0f, 0f, brightness,
            0f, 0f, contrast, 0f, brightness,
            0f, 0f, 0f, 1f, 0f
        ))
        val filtered = Bitmap.createBitmap(result.width, result.height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(filtered)
        val paint = Paint().apply { colorFilter = ColorMatrixColorFilter(cm) }
        canvas.drawBitmap(result, 0f, 0f, paint)
        result = filtered
    }

    // Apply scale
    if (adj.scale != 1f) {
        val matrix = Matrix().apply {
            postScale(adj.scale, adj.scale, result.width / 2f, result.height / 2f)
        }
        result = Bitmap.createBitmap(result, 0, 0, result.width, result.height, matrix, true)
    }

    return result
}

private fun addImageToMediaStore(context: Context, file: File, filename: String) {
    try {
        val values = ContentValues().apply {
            put(MediaStore.Images.Media.DISPLAY_NAME, filename)
            put(MediaStore.Images.Media.MIME_TYPE, "image/jpeg")
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                put(MediaStore.Images.Media.RELATIVE_PATH, "Pictures/SnapSell")
                put(MediaStore.Images.Media.IS_PENDING, 0)
            }
        }

        val uri = context.contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values)
        uri?.let {
            context.contentResolver.openOutputStream(it)?.use { os ->
                file.inputStream().use { fis ->
                    fis.copyTo(os)
                }
            }
        }
    } catch (_: Exception) {
        // MediaStore insert is best-effort
    }
}